Milestone 3: API
Jmagero/bookstore pull request #3
Opened 2021-09-03 15:49 UTC by Jmagero

- [x] Refactored add book and remove book features to persist changes in the server.
- [x] Refactor the redux code using middleware to make async requests to the API.

2021-09-03 18:01 UTC, Emmyn5600 requested changes
## STATUS: CHANGES REQUESTED :recycle:

Hi, @Jmagero 

Great work on implementing the changes requested by the previous reviewer, however there are some issues to be solved before you get approved but you are almost there:muscle:. 
   
- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Changes required :writing_hand: 
       
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-09-03 18:01 UTC, Emmyn5600 commented on src/components/AddBook.js
>          />
- [ ] Let us make input field for both book name and categories as required, to prevent users to add empty data

![arr25](https://user-images.githubusercontent.com/55635977/132047109-1612256a-33ec-494c-a339-bb95490cad08.png)

2021-09-03 18:01 UTC, Emmyn5600 commented on src/components/DisplayBooks.js
> +import PropTypes from 'prop-types';
- [ ] Kindly, fix the eslint errors without disable line of code.

2021-09-03 18:01 UTC, Emmyn5600 commented on src/redux/books/books.js
> +
- [ ] Let us remove the console.log in the code that has been pushed.

![arr27](https://user-images.githubusercontent.com/55635977/132047317-cb343d24-8855-47b9-bcb4-fb89a34e51a2.png)

- [ ] For the better implementation as well as keep our code clean, you would have create a file to keep the API information and create folder reducer to keep the reducer info

![arr29](https://user-images.githubusercontent.com/55635977/132047599-3dd4f586-bd36-4854-86a5-b8c2ca07ef5f.png)

- [ ] The home route should be the last route, means that the ` <Route exact="/" component={home} /> ` has to be the last.
![arr28](https://user-images.githubusercontent.com/55635977/132048048-1e2ff68c-0e19-4f4f-9b2b-8246fa7a9dcb.png)

2021-09-03 19:44 UTC, Jmagero commented
- [x]  Made input field for both book name and categories as required, to prevent users to add empty data
- [x] Made home route  the last route
- [x]  Created a file to keep the API information and create a folder reducer to keep the reducer info
- [x] Let us remove the console.log in the code that has been pushed.
- [x] Kindly, fix the eslint errors without disable line of code.

2021-09-04 01:03 UTC, oxenprogrammer approved these changes
Hi @Jmagero , 

Good effort working on all the requested changes by the previous Code Reviewer.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-04 05:22 UTC, merged